### ISSUE TITLE
Planets?

### ISSUE THREAD

**Issue by Nzash** [Arziel1992/Z-S-Overview-Pack#4]
I have a question. None of the tabs I've checked show planets whatsoever. Unfortunately simply adding planets myself and saving the preset doesn't work as it doesn't save over the preset but instead makes a new one, _literally_ called something like "<color=0xFFFFFFFF>✈ --- Travel: All</color>" for example. It doesn't actually put the stuff in color properly and the field is too long for it to work right too.

So my first question is if there is an easy way to make small changes to any of your presets and save them properly?

Secondly, why do you not show planets anywhere? Say I'm out roaming lowsec and hunting down some other people to shoot, surely I would want to see stations, belts and planets especially for when I quickly use some narrow d-scans to tell whether someone is at a certain planet, or in a given belt etc.? 

Thank you

**Comment by Arziel1992** [comment]
We never considered planets as a hiding spot for players since a somewhat knowledgeable player will make a safe spot so it's harder to pinpoint him with only D-Scan.
With Deuce we will revise adding planets to presets that might benefit from them,
Keep in mind that we have to counterweight it with not cluttering the preset on the actual overview window.

As for the saving issue, FAQ:
https://github.com/Arziel1992/Z-S-Overview-Pack/blob/master/FAQ.md#if-i-click-save-to-commit-the-changes-the-preset-name-will-not-save-properly

**Comment by Nzash** [comment]
Thank you, I see I could just add planets and then open the .yaml in any decent text editor, try to find the preset in question and edit the name to make it look proper there, then import again. 

Appreciate it.
