### ISSUE TITLE
Missing NPC types in PvP +NPC profiles

### ISSUE THREAD

**Issue by Taverius** [Arziel1992/Z-S-Overview-Pack#5]
I've noticed a few, with typenames such as "Mission Caldari Cruiser", mostly from story missions.

Also missing from the exploration PvP profile.

**Comment by Arziel1992** [comment]
Welcome to the exciting world of `CCP entity categories`, where everything is a mess \o/

Yeah there's that issue, for some _stupid_ reason, CCP decided to just place all newly added mission entities into the `Entity` category instead of their respective `Mission NPC` category.

But this is tackled in a specific way in the pack at the moment.

PvE presets do have those missing Mission NPC entities enabled.  
PvP presets only have the general NPC entities enabled.

I know, it's not ideal to have that split, making you switch around active presets, and you are absolutely right.
The end goal (when I have more time) is to merge all PvP and PvE presets into useful PvX ones.
